# Permissions & Commands:
# skportals.reload - /skp reload (reloads the plugin)
# skullwarsportals.giveremover - /skp giveremover (player)
# skullwarsportals.deleteallportals - /skp removeallportals (Deletes all active portals)
# %NumberOfPortalsRemoved% (Returns the amount of portals removed on deletion)
destination:
  world: "Darkzone"  # CaSe SeNsItIvE
  x: -561
  y: 100
  z: 35

messages:
  no-portals-to-remove: "&e&lSkull&6&lWars &8» &cNo portals to remove."
  portal-delete-success: "&e&lSkull&6&lWars &8» &fSuccessfully removed &e%NumberOfPortalsRemoved% &fportals."
  portal-created: "&e&lSkull&6&lWars &8» &cDarkzone&f portal has been created."
  teleported: "&e&lSkull&6&lWars &8» &fYou have been teleported to the &cDarkzone"
  cannot-place: "&e&lSkull&6&lWars &8» &cYou are placing portal blocks too close to another portal."
  cannot-break: "&e&lSkull&6&lWars &8» &fYou must use a &cportal-remover&f in order to be able to break portals."
  no-permission: "&e&lSkull&6&lWars &8» &cYou don't have permission to use this command."
  remover-received: "&e&lSkull&6&lWars &8» &fYou have received a &ePortal Remover&f."
  player-not-found: "&e&lSkull&6&lWars &8» &ePlayer&f not found."
  reload: "&e&lSkull&6&lWars &8» &eSkullWarsPortals &f has been reloaded."
  reload-fail: "&e&lSkull&6&lWars &8» &eSkullWarsPortals &f has failed to reload. Check console for further information."
  reload-usage: "&e&lSkull&6&lWars &8» &fInvalid Usage. Try &e/skp reload&f."
  destination-not-found: "&e&lSkull&6&lWars &8» &fDestination world not found."

hologram:
  text:
    - "&4&l»&c&l»&4&l» &c&lDarkzone Portal &4&l«&c&l«&4&l«"
    - "&c&nPvP&7 is &a&nenabled&7 on the other side!"
  height: 3.0              # Height above the portal where the hologram will appear

items:
  portal-remover:
    type: STICK
    damage: 0
    name: "&6&lPortal &c&lRemover"
    lore:
      - "&8PORTAL REMOVER"
      - ""
      - "&8»&f By Right clicking a portal"
      - "&8»&f it will disappear!"
      - ""

skullwarsportals:
  usage:
    - "&6_____________.[ &2SkullWars Portals &6]._____________"
    - "&b/skullwarsportals reload &eReloads the plugin configuration."
    - "&b/skullwarsportals removeallportals &eRemoves all active portals."
    - "&b/skullwarsportals giveremover <player> &eGives a portal remover item to the specified player."
